### ISSUE TITLE
dataset improvement

### ISSUE THREAD

**Issue by monperrus** [KTH/learning4repair#2]
* add filter on space only
* concatenate with other dataset
* remove filter on tests

plus
* update data on CodRep
* add metrics in Reademe (number of tasks)

**Comment by chenzimin** [comment]
Fixed in CodRep-competition commit [e75f7ec](https://github.com/KTH/CodRep-competition/commit/e75f7ecac734ae4da708d15af89dea66bd3e2bb7)
